[[table]]

== 테이블 정보
---
::

[[batch-table]]


=== 테이블 목록

:: 배치 프레임워크에서 사용되는 테이블 목록은 다음과 같다.

[options="header"]
|===============
^|테이블명 ^|설명 
|BATCH_SERVER_GROUP|배치 작업이 구동될 논리적인 서버 묶음으로 서버그룹 명 및 분배 정책 정보를 관리함 ( Random , Cpu Based , Priority Based ) 
|BATCH_SERVER |배치 작업이 구동될 논리적인 서버 정보로 서버명 및 정책 정보를 관리함 
|BATCH_AGENT |배치 Agent의 URL 및 정책 정보를 관리함 
|BATCH_JOB_GROUP |배치 작업에 대한 논리적인 그룹 	
|BATCH_JOB_GROUP_NOTICE |배치 작업 그룹 통지설정 정보를 관리함(통지대상, 유형, 통지시점) 
|BATCH_JOB |배치 작업(Job)에 대한 정보. 작업명, 작업정의(CFG) 파일의 위치, 동시 실행 가능여부 및 로그레벨, Time Window, description 등을
						관리함 
|BATCH_JOB_SCHEDULE |배치 작업에 대한 스케줄 정보를 관리함
|BATCH_JOB_SCHEDULE_ONCE_DATE |배치 작업에 스케줄 정보 중 상세 날짜 정보를 관리함
|BATCH_JOB_SCHEDULE_ONCE_TIME |배치 작업에 스케줄 정보 중 상세 시간 정보를 관리함
|BATCH_PRE_JOB |배치 작업에 대한 선행작업 목록을 관리함
|BATCH_JOB_NOTICE |배치 작업 실행 시 통지설정 정보를 관리함(통지대상, 유형, 통지시점) 
|BATCH_DAEMON |배치 데몬에 대한 정의, 정책, 실행 정보를 관리함 
|BATCH_DAEMON_TRIGGER |데몬에 포함된 각 트리거에 대한 정의, 파라미터, 정책, 실행 정보를 관리함 
|BATCH_JOB_EXECUTION |배치 작업 실행 시 저장되는 작업 실행 이력  
|BATCH_STEP_EXECUTION |배치 작업 실행 시 저장되는 스텝 실행 이력 
|BATCH_RESOURCE_EXECUTION |배치 작업 실행 시 저장되는 리소스 이력 
|BATCH_JOB_EXECUTION_EVENT |스케줄 배치 작업 실행에 대한 이벤트 이력
|BATCH_CONFIG |일일 스케줄링 시간 리더 어드민 관련 설정을 관리함
|BATCH_REPLACE_PARAM |시스템 파라메터 정보를 관리함
|BATCH_TIMEZONE |스케줄링 타임존 정보를 관리함

|===============


[[batch-table-specification]]


=== 테이블 명세서

.BATCH_SERVER_GROUP
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|NAME |VARCHAR2 |500 |N |배치 서버 그룹명 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|ALGORITHM |VARCHAR2 |30 |Y |배치 작업 분배 알고리즘 ( RANDOM / CPU / PRIORITY )

|=============== 

.BATCH_SERVER
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|NAME |VARCHAR2 |500 |N |배치 서버 명 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|MAX_JOB |NUMBER |22 |Y |최대 허용 작업 수 
|BLOCK |CHAR |1 |Y |배치 작업 대기 여부 
|ALLOW_KILL |CHAR |1 |Y |작업 중지 허용 여부 
|ALLOW_RUN |CHAR |1 |Y |작업 실행 허용 여부 
|ALLOW_STOP |CHAR |1 |Y |작업 정지 하용 여부 
|ALLOW_ADDRESS |VARCHAR2 |4000 |Y |접근 허용 IP 설정 
|CPU_CURRENT |NUMBER |10,5 |Y |CPU 사용량
|PRIORITY |NUMBER |2 |Y |서버의 우선순위 ( 서버 그룹의 분배알고리즘 중 PRIORITY 와 연관됨 )

|===============


.BATCH_AGENT
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|NAME |VARCHAR2 |500 |N |에이전트명 
|SERVER_NAME |VARCHAR2 |500 |N |서버 명 
|URL |VARCHAR2 |1000 |Y |에이전트 URL 
|STATUS |VARCHAR2 |30 |Y |에이전트 상태 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|MEMORY_TOTAL |NUMBER |20 |Y |메모리 사용량
|MEMORY_FREE |NUMBER |20 |Y |여유 메모리 량
|CPU_CURRENT |NUMBER |10,5 |Y |CPU 사용량

|===============


.BATCH_JOB_GROUP
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|GROUP_NAME |VARCHAR2 |500 |N |배치 작업 그룹명 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|TARGET |VARCHAR2 |100 |Y |실행 서버 
|TARGET_TYPE |VARCHAR2 |30 |Y |실행 서버 유형 ( SERVERGROUP, SERVER )
|CONCURRENT |CHAR |1 |Y |동시실행여부
|CONCURRENT_COUNT |NUMBER |20 |Y |최대 동시실행 개수
|ENABLE |CHAR |1 |Y |작업 사용 여부 
|WINDOW_ENABLE |CHAR |1 |Y |작업 수행 시간 지정 여부 
|WINDOW_FROM |VARCHAR2 |40 |Y |작업 수행 시작 시간 
|WINDOW_TO |VARCHAR2 |40 |Y |작업 수행 종료 시간 
|TO_MINUTE |VARCHAR2 |40 |Y |작업 수행 종료 시간 (분)
|FROM_MINUTE |VARCHAR2 |40 |Y |작업 수행 시작 시간 (분)
|LOG_LEVEL |VARCHAR2 |20 |Y |로그 레벨 타입 

|===============

.BATCH_JOB_GROUP_NOTICE
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|GROUP_NAME |VARCHAR2 |500 |N |통지 작업그룹명 
|TARGET_TYPE |VARCHAR2 |100 |N |통지 주체 타입 
|SEND_TYPE |VARCHAR2 |100 |N |통지 타입 
|NOTICE_START |CHAR |1 |Y |시작시 통지 여부 
|NOTICE_COMPLETE |CHAR |1 |Y |완료시 통지 여부 
|NOTICE_ERROR |CHAR |1 |Y |에러시 통지 여부 
|===============

.BATCH_JOB
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |500 |N |배치 작업 명 
|LOCATION |VARCHAR2 |1000 |N |CFG 경로 
|AUTHOR |VARCHAR2 |200 |N |배치 권한자 
|GROUP_NAME |VARCHAR2 |500 |Y |배치 그룹명 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|PARAMETERS |VARCHAR2 |4000 |Y |작업 파라메터 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |배치 작업 생성 일시 
|MODIFY_TIME |TIMESTAMP(6) |11 |Y |배치 작업 수정 일시 
|TARGET |VARCHAR2 |100 |Y |실행 서버 
|ENABLE |CHAR |1 |Y |작업 사용 여부 
|CONCURRENT |CHAR |1 |Y |동시실행여부 
|CONCURRENT_COUNT |NUMBER |20 |Y |최대 동시실행 개수
|WINDOW_ENABLE |CHAR |1 |Y |작업 수행 시간 지정 여부 
|WINDOW_FROM |VARCHAR2 |40 |Y |작업 수행 시작 시간 
|WINDOW_TO |VARCHAR2 |40 |Y |작업 수행 종료 시간 
|LOG_LEVEL |VARCHAR2 |20 |Y |로그 레벨 타입 
|COMMAND |VARCHAR2 |500 |Y |명령어 
|DIRECTORY |VARCHAR2 |500 |Y |명령어 디렉토리명 
|JOB_TYPE |VARCHAR2 |30 |Y |작업 타입 ( BATCH, SHELL )
|TARGET_TYPE |VARCHAR2 |30 |Y |실행 서버 유형 ( SERVERGROUP, SERVER )
|EXECUTION_TYPE |VARCHAR2 |30 |Y |실행 타입 ( PROCESS, THREAD )
|GROUP_POLICY |CHAR |1 |Y |그룹 설정 사용 여부
|===============

.BATCH_JOB_SCHDULE
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |500 |N |작업명 
|PERIOD_DAY_TYPE |VARCHAR2 |10 |Y |스케줄 날짜 타입 ( ONCE, DAY 등 )
|PERIOD_TIME_TYPE |VARCHAR2 |10 |Y |스케줄 시간 타입 ( TIMEONCE, TIMEHOUR 등 )
|START_DAY |DATE |- |Y |시작일
|START_FG |VARCHAR2 |1 |Y |시작일 사용여부
|EXPIRED_DAY |DATE |- |Y |종료일
|EXPIRED_FG |VARCHAR2 |1 |Y |종료일 사용여부
|EXECUTION_TIME |DATE |- |Y |실행 시간
|SCHEDULE_MONTHDAY |NUMBER |10 |Y |월별 날짜 스케줄 정보 ( 매월 말일 )
|SCHEDULE_WEEKDAY |NUMBER |3 |Y |월별 주별 날짜 스케줄 정보 ( 매월 3째주 월요일 )
|SCHEDULE_WEEK |NUMBER |3 |Y |주별 날짜 스케줄 정보 ( 매주 월요일 )
|SCHEDULE_MONTH |NUMBER |4 |Y |월별 월 스케줄 정보 ( 1월,3월 )
|PERIOD_INTERVAL |NUMBER |5 |Y |기간 주기 ( 매 2일 , 매 2주 )
|EXECUTION_MIN |NUMBER |2 |Y |실행 시간 (분)
|EXECUTION_SEC |NUMBER |2 |Y |실행 시간 (초)
|SCHEDULE_HOUR |NUMBER |8 |Y |스케줄 시간 (시간)
|SCHEDULE_MIN |NUMBER |19 |Y |스케줄 시간 (분)
|SCHEDULE_SEC |NUMBER |19 |Y |스케줄 시간 (초)
|START_TIME_HOUR |NUMBER |2 |Y |하루 중 시작 시간 (시간) 
|START_TIME_MIN |NUMBER |2 |Y |하루 중 시작 시간 (분) 
|START_TIME_HOUR |NUMBER |2 |Y |하루 중 종료 시간 (시간) 
|START_TIME_HOUR |NUMBER |2 |Y |하루 중 종료 시간 (분) 
|TIME_INTERVAL |NUMBER |5 |Y |스케줄 주기 정보
|TIME_INTERVAL_UNIT |VARCHAR2 |10 |Y |스케줄 주기 단위
|TIME_INTERVAL_TYPE |VARCHAR2 |10 |Y |스케줄 주기 유형
|CRON_STRING |VARCHAR2 |100 |Y |Cron 문자열
|TIMEZONE_ID |VARCHAR2 |100 |Y |타임존 ID
|===============

.BATCH_JOB_SCHDULE_ONCE_DATE
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |100 |N |작업명 
|ONCE_DATE_SEQ |NUMBER |10 |N |스케줄 날짜 상세정보 SEQUENCE 
|SCHE_YEAR |VARCHAR2 |4 |N |스케줄 년 정보
|SCHE_MONTH |VARCHAR2 |2 |N |스케줄 월 정보
|SCHE_DAY |VARCHAR2 |2 |N |스케줄 일 정보
|===============

.BATCH_JOB_SCHDULE_ONCE_TIME
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |100 |N |작업명 
|ONCE_TIME_SEQ |NUMBER |10 |N |스케줄 시간 상세정보 SEQUENCE 
|SCHE_HOUR |NUMBER |2 |Y |스케줄 시간 정보
|SCHE_MIN |NUMBER |2 |Y |스케줄 분 정보
|SCHE_SEC |NUMBER |2 |Y |스케줄 초 정보
|===============

.BATCH_PRE_JOB
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |500 |N |작업명 
|PRE_JOB_SEQ |NUMBER |10 |N |선행 작업 SEQUENCE
|PRE_JOB_NAME |VARCHAR |500 |N |선행 작업 명
|===============

.BATCH_JOB_NOTICE
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_NAME |VARCHAR2 |500 |N |통지 작업명 
|TARGET_TYPE |VARCHAR2 |100 |N |통지 주체 타입 
|SEND_TYPE |VARCHAR2 |100 |N |통지 타입 
|NOTICE_START |CHAR |1 |Y |시작시 통지 여부 
|NOTICE_COMPLETE |CHAR |1 |Y |완료시 통지 여부 
|NOTICE_ERROR |CHAR |1 |Y |에러시 통지 여부 
|GROUP_POLICY |CHAR |1 |Y |그룹 설정 사용 여부

|===============


.BATCH_DAEMON
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|DAEMON_NAME |VARCHAR2 |500 |N |데몬명 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|TARGET |VARCHAR2 |100 |Y |실행 에이전트명 
|SERVER |VARCHAR2 |100 |Y |실행 서버명 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |데몬 생성 일시 
|MODIFY_TIME |TIMESTAMP(6) |11 |Y |데몬 수정 일시 
|ENABLE |CHAR |1 |Y |사용가능여부 
|AUTO_RESTART |CHAR |1 |Y |자동재실행여부 
|STATUS |VARCHAR2 |20 |Y |데몬상태 
|PID |VARCHAR2 |30 |Y |프로세스 ID 
|START_TIME |TIMESTAMP(6) |11 |Y |데몬 시작 일시 
|UPDATE_TIME |TIMESTAMP(6) |11 |Y |데몬 갱신 일시 
|LOG_FILE |VARCHAR2 |1000 |Y |마지막 실행 일시 
|EXIT_MESSAGE |VARCHAR2 |4000 |Y |종료 메시지 
|AUTHOR |VARCHAR2 |200 |Y |데몬 권한자 
|NOTICE_ADMIN_TYPE |VARCHAR2 |100 |Y |시스템 권한자 통지 타입  
|NOTICE_ADMIN_START |CHAR |1 |Y |시스템 권한자 시작시 통지여부 
|NOTICE_ADMIN_END |CHAR |1 |Y |시스템 권한자 비정상 통지여부 
|NOTICE_AUTHOR_TYPE |VARCHAR2 |100 |Y |데몬 권한자 통지 타입 
|NOTICE_AUTHOR_START |CHAR |1 |Y |데몬 권한자 시작시 통지 여부 
|NOTICE_AUTHOR_END |CHAR |1 |Y |데몬 권한자 비정상 통지 여부 
|NOTICE_INTERVAL |NUMBER |22 |Y |자동재실행 주기 
|THREAD_COUNT |NUMBER |4 |Y |데몬 쓰레드 사용개수     
|CPU_CURRENT |NUMBER  |10,5 |Y |cpu 현재 사용량
|CPU_AVERAGE |NUMBER  |10,5 |Y |cpu 평균 사용량
|MEMORY_TOTAL |NUMBER  |20 |Y |총 메모리 사용량
|MEMORY_FREE |NUMBER  |20 |Y |메모리 여유량

|===============


.BATCH_DAEMON_TRIGGER
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|DAEMON_NAME |VARCHAR2 |500 |N |데몬명 
|TRIGGER_NAME |VARCHAR2 |500 |N |트리거명 
|JOB_LOCATION |VARCHAR2 |1000 |N |CFG 경로 
|AUTHOR |VARCHAR2 |20 |N |권한자 
|DESCRIPTION |VARCHAR2 |4000 |Y |기재사항 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |트리거 생성일시 
|MODIFY_TIME |TIMESTAMP(6) |11 |Y |트리거 수정일시 
|PARAMETERS |VARCHAR2 |4000 |Y |트리거 파라메터 
|TYPE |VARCHAR2 |20 |Y |트리거 타입 
|FIXED_RATE |CHAR |1 |Y |타이머 트리거 고정주기 여부 
|INPUT_DIRECTORY |VARCHAR2 |1000 |Y |파일 트리거 입력 파일 경로 
|INPUT_FILE |VARCHAR2 |4000 |Y |파일 트리거 입력 파일명 
|OUTPUT_DIRECTORY |VARCHAR2 |1000 |Y |파일 트리거 출력 파일 경로 
|SCHEDULE |VARCHAR2 |20 |Y |스케쥴 트리거 설정 내용 
|INTERVAL |NUMBER |22 |Y |타이머 트리거 주기 
|ENABLE |CHAR |1 |Y |트리거 사용 여부 
|CONCURRENT |CHAR |1 |Y |트리거 동시 실행 여부 
|WINDOW_ENABLE |CHAR |1 |Y |트리거 수행 시간 지정 여부 
|WINDOW_FROM |VARCHAR2 |40 |Y |트리거 수행 시작 시간 
|WINDOW_TO |VARCHAR2 |40 |Y |트리거 수행 종료 시간 
|LOG_LEVEL |VARCHAR2 |20 |Y |로그 레벨 타입 
|STATUS |VARCHAR2 |20 |Y |트리거상태 
|TOTAL_EXECUTION |NUMBER |22 |Y |트리거 수행 횟수 
|LAST_EXECUTION |TIMESTAMP(6) |11 |Y |트리거 갱신 일시 
|LOG_FILE |VARCHAR2 |1000 |Y |트리거 로그 파일 경로 
|EXIT_MESSAGE |VARCHAR2 |4000 |Y |트리거 종료 메시지 

|===============


.BATCH_JOB_EXECUTION
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_ID |NUMBER |22 |N |작업 고유ID (BATCH_JOB_EXECUTION_SEQ 사용) 
|JOB_NAME |VARCHAR2 |500 |N |배치 작업명 (CFG 파일명) 
|STATUS |VARCHAR2 |20 |Y |배치 작업 상태 
|EXIT_MESSAGE |VARCHAR2 |2500 |Y |배치 작업 로그 경로 
|LOG_FILE |VARCHAR2 |500 |Y |배치 작업 로그 파일 경로 
|SHORT_CONTEXT |VARCHAR2 |2500 |Y |작업 파라메터 (2500Byte 미만) 
|SERIALIZED_CONTEXT |CLOB |4000 |Y |작업 파라메터 (2500Byte 이상) 
|THREAD_COUNT |NUMBER |22 |Y |배치 프로세스 THREAD 수 
|CPU_CURRENT |NUMBER |22 |Y |현재 CPU 사용량 
|CPU_AVERAGE |NUMBER |22 |Y |평균 CPU 사용량 
|MEMORY_TOTAL |NUMBER |22 |Y |전체 메모리 사용량 
|MEMORY_FREE |NUMBER |22 |Y |여유 메모리양 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |배치 작업 생성일시 
|UPDATE_TIME |TIMESTAMP(6) |11 |Y |배치 작업 갱신일시 
|VERSION |NUMBER |22 |Y |배치 작업 수행 횟수 
|JOB_KEY |VARCHAR2 |2500 |Y |배치 작업 키 (External Key) 
|JOB_TYPE |VARCHAR2 |30 |Y |배치 작업 타입 (NORMAL , ONLINE , DAEMON) 
|JOB_LOCATION |VARCHAR2 |500 |Y |배치 작업정의(CFG) 경로 
|JOB_ARGUMENT |VARCHAR2 |2500 |Y |배치 실행시 전달 파라메터 
|JOB_EXEC_YN |VARCHAR2 |1 |Y |작업 실행 여부 
|SERVER |VARCHAR2 |100 |Y |실행 서버명 
|IP |VARCHAR2 |20 |Y |실행 에이전트 IP 
|PID |VARCHAR2 |30 |Y |프로세스 ID 
|SCHEDULE_TIME |TIMESTAMP |6 |Y |스케줄 시간
|MONITOR_CHECK_YN |CHAR |1 |Y |어드민 모니터링 여부
|COMMAND |VARCHAR2 |1000 |Y |작업 실행 명령어
|OPERATION_DATE |VARCHAR2 |10 |Y |실행일 정보
|JOB_EXECUTION_KEY |VARCHAR2 |100 |Y |작업 sub-key
|RUNTIME_INSTANCE_NAME |VARCHAR2 |100 |Y |작업 실행 인스턴스 명 ( THREAD 실행인 경우 )
|STEP_TOTAL |NUMBER |5 |Y |총 스텝개수
|TIMEZONE_ID |VARCHAR2 |100 |Y |타임존 ID
|===============


.BATCH_STEP_EXECUTION
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_ID |NUMBER |22 |N |작업 고유ID 
|STEP_ID |NUMBER |22 |N |스텝 고유ID (BATCH_STEP_EXECUTION_SEQ 사용) 
|STEP_NAME |VARCHAR2 |500 |N |배치 스텝명 
|STATUS |VARCHAR2 |20 |Y |배치 스텝 상태 
|EXIT_MESSAGE |VARCHAR2 |2500 |Y |출력 메시지 
|LOG_FILE |VARCHAR2 |500 |Y |배치 스텝 로그 위치 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |배치 스텝 생성일시 
|UPDATE_TIME |TIMESTAMP(6) |11 |Y |배치 스텝 수정일시 
|SHORT_CONTEXT |VARCHAR2 |2500 |Y |스텝 파라메터 (2500Byte 미만) 
|SERIALIZED_CONTEXT |CLOB |4000 |Y |스텝 파라메터 (2500Byte 이상) 
|CPU_CURRENT |NUMBER |22 |Y |현재 CPU사용량 
|CPU_AVERAGE |NUMBER |22 |Y |평균 CPU사용량 
|MEMORY_TOTAL |NUMBER |22 |Y |전체 메모리 사용량 
|MEMORY_FREE |NUMBER |22 |Y |여유 메모리양 
|CURRENT_COUNT |NUMBER |22 |Y |N/A 
|TOTAL_COUNT |NUMBER |22 |Y |N/A 
|COMMIT_COUNT |NUMBER |22 |Y |커밋 횟수 
|VERSION |NUMBER |22 |Y |수행된 횟수 
|MAX_COMMIT_INTERVAL |NUMBER |38 |Y |최대 commit count 저장

|===============


.BATCH_RESOURCE_EXECUTION
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_ID |NUMBER |22 |N |작업 고유ID 
|STEP_ID |NUMBER |22 |N |스텝 고유ID 
|RESOURCE_NAME |VARCHAR2 |500 |N |리소명 
|URL |VARCHAR2 |2000 |Y |리소스 URL 
|IO_TYPE |VARCHAR2 |10 |N |입출력 유형 (READ , WRITE , UPDATE , UNKNOWN) 
|RESOURCE_TYPE |VARCHAR2 |10 |Y |리소스 타입 (FILE , DB , UNKNOWN) 
|STATUS |VARCHAR2 |10 |Y |리소스 상태 (LOCKED , RELEASED) 
|CURRENT_COUNT |NUMBER |22 |Y |현재 READ/WRITE 횟수 
|COMMIT_POS |NUMBER |22 |Y |커밋 시점 리소스 위치 
|COMMIT_COUNT |NUMBER |22 |Y |커밋 시 READ/WRTIE 횟수 
|CREATE_TIME |TIMESTAMP(6) |11 |Y |리소스 생성일시 
|UPDATE_TIME |TIMESTAMP(6) |11 |Y |리소스 갱신일시 

|===============


.BATCH_JOB_EXECUTION_EVENT
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|JOB_ID |NUMBER |19 |N |작업 고유ID 
|EVENT_DATE |NUMBER |20 |N |이벤트 시간    
|EVENT_INFO |VARCHAR2 |100 |Y |이벤트 정보 
|===============

.BATCH_CONFIG
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|SCHEDULING_TIME |VARCHAR2 |30 |N |일일 스케줄링 시간
|LEADER_ADMIN_NAME |VATCHAR2 |100 |Y |리더 어드민 URL
|LEADER_ADMIN_UPDATE_TIME |TIMESTAMP |6 |Y |리더 어드민 최근 health check 시간
|===============

.BATCH_REPLACE_PARAM
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|REPLACE_KEY |VARCHAR2 |100 |N |시스템 파라메터 키
|REPLACE_TYPE |VARCHAR2 |30 |Y |시스템 파라메터 유형 ( JOB_NAME, OPERATION_DATE, VALUE )
|REPLACE_VALUE |VARCHAR2 |100 |Y |시스템 파라메터 값
|REPLACE_OFFSET |NUMBER |2 |Y |날짜유형인 경우 offset
|===============

.BATCH_TIMEZONE
[options="header"]
|===============
^|NAME ^|TYPE ^|LENGTH ^|NULLABLE ^|COMMNETS 
|TIMEZONE_ID |VARCHAR2 |100 |N |타임존 ID
|DEFAULT_YN |VARCHAR2 |1 |N |default 여부
|===============

[[batch-table-ddl]]


=== DDL

:: 
[source, sql]
----
CREATE TABLE BATCH_SERVER_GROUP
(
  NAME VARCHAR2(500) NOT NULL,
  DESCRIPTION VARCHAR2(4000),
  ALGORITHM VARCHAR2(30),
  CONSTRAINT BATCH_SERVER_GROUP_PK PRIMARY KEY (NAME)
);
----

[source, sql]
----

CREATE TABLE BATCH_SERVER (
		NAME 				VARCHAR2(500) 	NOT NULL,
		SERVER_GROUP_NAME   VARCHAR2(500) 	NOT NULL,
		DESCRIPTION 		VARCHAR2(4000),
		MAX_JOB 			NUMBER(20),
		BLOCK 				CHAR(1),
		ALLOW_KILL 			CHAR(1),
		ALLOW_RUN 			CHAR(1),
		ALLOW_STOP 			CHAR(1),
		ALLOW_ADDRESS 		VARCHAR2(4000),
		PRIORITY			NUMBER(1),
		CPU_CURRENT			NUMBER(10,5)	DEFAULT 0
	);

CREATE UNIQUE INDEX BATCH_SERVER_PK ON BATCH_SERVER (NAME);

----


[source, sql]
----

CREATE TABLE BATCH_AGENT (
		NAME 				VARCHAR2(500) 	NOT NULL,
		SERVER_NAME 		VARCHAR2(500) 	NOT NULL,
		URL 				VARCHAR2(1000),
		STATUS 				VARCHAR2(30),
		DESCRIPTION 		VARCHAR2(4000),
		CPU_CURRENT			NUMBER(10,5),
		MEMORY_TOTAL		NUMBER(20),
		MEMORY_FREE			NUMBER(20)
);
	
CREATE UNIQUE INDEX BATCH_AGENT_PK ON BATCH_AGENT (NAME, SERVER_NAME);

----


[source, sql]
----

CREATE TABLE BATCH_JOB_GROUP
(
	GROUP_NAME					VARCHAR2(500) 	NOT NULL,
	DESCRIPTION					VARCHAR2(4000),
  TARGET              VARCHAR2(100), 
  TARGET_TYPE         VARCHAR2(30),
  ENABLE              CHAR(1), 
  CONCURRENT          CHAR(1), 
  CONCURRENT_COUNT    DECIMAL(20,0), 
  WINDOW_ENABLE       CHAR(1), 
  WINDOW_FROM         VARCHAR2(40), 
  WINDOW_TO           VARCHAR2(40), 
  TO_MINUTE           VARCHAR2(40),
  FROM_MINUTE         VARCHAR2(40),
  LOG_LEVEL           VARCHAR2(20)
);

CREATE UNIQUE INDEX BATCH_JOB_GROUP_PK ON BATCH_JOB_GROUP (GROUP_NAME);

----


[source, sql]
----

CREATE TABLE BATCH_JOB_GROUP_NOTICE
(
  GROUP_NAME        VARCHAR2(500) NOT NULL ENABLE, 
  TARGET_TYPE       VARCHAR2(100) NOT NULL ENABLE, 
  SEND_TYPE         VARCHAR2(100) NOT NULL ENABLE, 
  NOTICE_START      CHAR(1), 
  NOTICE_COMPLETE   CHAR(1), 
  NOTICE_ERROR      CHAR(1)
);

CREATE UNIQUE INDEX BATCH_JOB_GROUP_NOTICE_PK ON BATCH_JOB_GROUP_NOTICE (GROUP_NAME, TARGET_TYPE);

----


[source, sql]
----

CREATE TABLE BATCH_JOB (
	JOB_NAME 					  VARCHAR2(500) 	NOT NULL,
	LOCATION 					  VARCHAR2(1000),
	AUTHOR 						  VARCHAR2(200) 	NOT NULL,
	GROUP_NAME 					VARCHAR2(500),
	DESCRIPTION 				VARCHAR2(4000),
	PARAMETERS 					VARCHAR2(4000),
	CREATE_TIME 				TIMESTAMP,
	MODIFY_TIME					TIMESTAMP,
	TARGET	  					VARCHAR2(100),
	ENABLE 		  				CHAR(1),
	CONCURRENT 					CHAR(1),
	CONCURRENT_COUNT		NUMBER(20),
	WINDOW_ENABLE 			CHAR(1),
	WINDOW_FROM					VARCHAR2(40),
	WINDOW_TO				  	VARCHAR2(40),
	LOG_LEVEL 				 	VARCHAR2(20),
	COMMAND            	VARCHAR2(500),  
	DIRECTORY        	  VARCHAR2(500),  
	JOB_TYPE					  VARCHAR2(30),   
	TARGET_TYPE					VARCHAR2(30),
	EXECUTION_TYPE			VARCHAR2(30),
  GROUP_POLICY CHAR(1)
);
	
CREATE UNIQUE INDEX BATCH_JOB_PK ON BATCH_JOB (JOB_NAME);

----


[source, sql]
----




CREATE TABLE BATCH_JOB_SCHEDULE
(
  JOB_NAME        VARCHAR2(100)          NOT NULL,
  PERIOD_DAY_TYPE    VARCHAR2(10),
  PERIOD_TIME_TYPE   VARCHAR2(10),
  START_DAY          DATE,
  START_FG           VARCHAR2(1),
  EXPIRED_DAY        DATE,
  EXPIRED_FG         VARCHAR2(1),
  EXECUTION_TIME     DATE,
  SCHEDULE_MONTHDAY  NUMBER(10),
  SCHEDULE_WEEKDAY   NUMBER(3),
  SCHEDULE_WEEK      NUMBER(3),
  SCHEDULE_MONTH     NUMBER(4),
  PERIOD_INTERVAL    NUMBER(5),
  EXECUTION_MIN      NUMBER(2),
  EXECUTION_SEC      NUMBER(2),
  SCHEDULE_HOUR      NUMBER(8),
  SCHEDULE_MIN       NUMBER(19),
  SCHEDULE_SEC       NUMBER(19),
  START_TIME_HOUR      NUMBER(2),
  START_TIME_MIN     NUMBER(2),
  EXPIRED_TIME_HOUR  NUMBER(2),
  EXPIRED_TIME_MIN   NUMBER(2),
  TIME_INTERVAL      NUMBER(5),
  TIME_INTERVAL_UNIT VARCHAR2(10),
  TIME_INTERVAL_TYPE VARCHAR2(10),
  CRON_STRING          VARCHAR2(100),
  TIMEZONE_ID     VARCHAR2(100),
  CONSTRAINT BATCH_JOB_SCHEDULE_PK PRIMARY KEY (JOB_NAME)
);
----


[source, sql]
----

CREATE TABLE BATCH_JOB_SCHEDULE_ONCE_TIME
(
  JOB_NAME            VARCHAR2(100)      NOT NULL,
  ONCE_TIME_SEQ       number(10)       NOT NULL,
  SCHE_HOUR              NUMBER(2)              DEFAULT '0',
  SCHE_MIN               NUMBER(2)              DEFAULT '0',
  SCHE_SEC               NUMBER(2)              DEFAULT '0',
  CONSTRAINT BATCH_SCHEDULE_ONCE_TIME_PK PRIMARY KEY (JOB_NAME, ONCE_TIME_SEQ),
  CONSTRAINT BATCH_SCHEDULE_ONCE_TIME_FK FOREIGN KEY (JOB_NAME)  REFERENCES BATCH_JOB_SCHEDULE (JOB_NAME) ENABLE
);
----


[source, sql]
----


CREATE TABLE BATCH_JOB_SCHEDULE_ONCE_DATE
(
  JOB_NAME      VARCHAR2(100)            NOT NULL,
  ONCE_DATE_SEQ       number(10)       NOT NULL,
  SCHE_YEAR         VARCHAR2(4),
  SCHE_MONTH        VARCHAR2(2),
  SCHE_DAY          VARCHAR2(2),
  CONSTRAINT BATCH_SCHEDULE_ONCE_DATE_PK PRIMARY KEY (JOB_NAME, ONCE_DATE_SEQ),
  CONSTRAINT BATCH_SCHEDULE_ONCE_DATE_FK FOREIGN KEY (JOB_NAME)  REFERENCES BATCH_JOB_SCHEDULE (JOB_NAME) ENABLE
);
----


[source, sql]
----


CREATE TABLE BATCH_PRE_JOB
(
  JOB_NAME VARCHAR2(500)   NOT NULL,
  PRE_JOB_SEQ NUMBER(10)   NOT NULL,
  PRE_JOB_NAME VARCHAR2(500)   NOT NULL,
  CONSTRAINT BATCH_PRE_JOB_PK PRIMARY KEY (JOB_NAME, PRE_JOB_SEQ)
);
----

[source, sql]
----

CREATE TABLE BATCH_JOB_NOTICE
(
	JOB_NAME 					VARCHAR2(500) 	NOT NULL,
	TARGET_TYPE 				VARCHAR2(100) 	NOT NULL,
	SEND_TYPE 					VARCHAR2(100) 	NOT NULL,
	NOTICE_START 				CHAR(1),
	NOTICE_COMPLETE 			CHAR(1),
	NOTICE_ERROR 				CHAR(1),
  GROUP_POLICY CHAR(1)
);
	
CREATE UNIQUE INDEX BATCH_JOB_NOTICE_PK ON BATCH_JOB_NOTICE (JOB_NAME, TARGET_TYPE);

----


[source, sql]
----

CREATE TABLE BATCH_DAEMON (
	-- definition
	DAEMON_NAME 				VARCHAR2(500) 	NOT NULL,
	DESCRIPTION 				VARCHAR2(4000),
	TARGET						VARCHAR2(100),
	SERVER						VARCHAR2(100),
	CREATE_TIME 				TIMESTAMP,
	MODIFY_TIME					TIMESTAMP,

	-- policy
	ENABLE 						CHAR(1),
	AUTO_RESTART				CHAR(1),
	
	-- execution
	STATUS						VARCHAR2(20),
	PID							VARCHAR2(30),
	START_TIME					TIMESTAMP,
	UPDATE_TIME 				TIMESTAMP,
	LOG_FILE         			VARCHAR2(1000),
	EXIT_MESSAGE				VARCHAR2(4000),
	
	--notice
	AUTHOR 						VARCHAR2(200), 
	NOTICE_ADMIN_TYPE 			VARCHAR2(100), 
	NOTICE_ADMIN_START 			CHAR(1), 
	NOTICE_ADMIN_END 			CHAR(1), 
	NOTICE_AUTHOR_TYPE 			VARCHAR2(100), 
	NOTICE_AUTHOR_START 		CHAR(1), 
	NOTICE_AUTHOR_END 			CHAR(1),
	NOTICE_INTERVAL   			NUMBER(4),
	
	-- health
	THREAD_COUNT			NUMBER(4),
	CPU_CURRENT				NUMBER(10,5),
	CPU_AVERAGE				NUMBER(10,5),
	MEMORY_TOTAL			NUMBER(20),
	MEMORY_FREE				NUMBER(20)
);

CREATE UNIQUE INDEX BATCH_DAEMON_PK ON BATCH_DAEMON (DAEMON_NAME);	

----




[source, sql]
----

CREATE TABLE BATCH_DAEMON_TRIGGER (
	-- definition
	DAEMON_NAME 				VARCHAR2(500) 	NOT NULL,
	TRIGGER_NAME				VARCHAR2(500) 	NOT NULL,
	JOB_LOCATION				VARCHAR2(1000) 	NOT NULL,	-- BATCH JOB LOCATION (CFG.XML)
	AUTHOR 						VARCHAR2(20) 	NOT NULL,
	DESCRIPTION 				VARCHAR2(4000),
	CREATE_TIME 				TIMESTAMP,
	MODIFY_TIME					TIMESTAMP,

	-- parameters
	PARAMETERS 					VARCHAR2(4000),
	
	-- trigger
	TYPE 						VARCHAR2(20),	-- TRIGGER TYPE: FILE | TIMER | SCHEDULE
	FIXED_RATE 					CHAR(1),
	INPUT_DIRECTORY 			VARCHAR2(1000),
	INPUT_FILE 					VARCHAR2(4000),
	OUTPUT_DIRECTORY 			VARCHAR2(1000),
	SCHEDULE 					VARCHAR2(200),
	TIMER_INTERVAL 				NUMBER(20),

	-- policy
	ENABLE 						CHAR(1),
	CONCURRENT 					CHAR(1),
	WINDOW_ENABLE 				CHAR(1),
	WINDOW_FROM					VARCHAR2(40),
	WINDOW_TO					VARCHAR2(40),
	LOG_LEVEL 					VARCHAR2(20),

	-- execution
	STATUS						VARCHAR2(20),
	TOTAL_EXECUTION 			NUMBER(20),
	START_TIME					TIMESTAMP,
	LAST_EXECUTION 				TIMESTAMP,
	LOG_FILE         			VARCHAR2(1000),
	EXIT_MESSAGE				VARCHAR2(4000)
);

CREATE UNIQUE INDEX BATCH_DAEMON_TRIGGER_PK ON BATCH_DAEMON_TRIGGER (DAEMON_NAME, TRIGGER_NAME);

----




[source, sql]
----

CREATE TABLE BATCH_JOB_EXECUTION
(
  JOB_ID					    NUMBER(19)		NOT NULL,
  JOB_NAME					  VARCHAR2(500)	NOT NULL,
  STATUS					    VARCHAR2(20),
  EXIT_MESSAGE				VARCHAR2(2500),
  LOG_FILE					  VARCHAR2(500),
  SHORT_CONTEXT 			VARCHAR2(2500),
  SERIALIZED_CONTEXT  CLOB,
  THREAD_COUNT			  NUMBER(4),
  CPU_CURRENT				  NUMBER(10,5),
  CPU_AVERAGE				  NUMBER(10,5),
  MEMORY_TOTAL			  NUMBER(20),
  MEMORY_FREE				  NUMBER(20),
  CREATE_TIME				  TIMESTAMP(6),
  UPDATE_TIME				  TIMESTAMP(6),
  VERSION 					  NUMBER(19,0),
  JOB_KEY					    VARCHAR2(2500),
  JOB_TYPE					  VARCHAR2(30),
  JOB_LOCATION			  VARCHAR2(500),
  JOB_ARGUMENT		    VARCHAR2(2500),
  JOB_EXEC_YN			    VARCHAR2(1),
  SERVER					    VARCHAR2(100),
  IP						      VARCHAR2(20),
  PID						      VARCHAR2(30),
  MONITOR_CHECK_YN	  CHAR(1),
  COMMAND					    VARCHAR2(1000),
  OPERATION_DATE      VARCHAR2(10),    
  JOB_EXECUTION_KEY   VARCHAR2(100),  
  RUNTIME_INSTANCE_NAME VARCHAR2(100), 
  STEP_TOTAL DECIMAL(5,0),            
  SCHEDULE_TIME TIMESTAMP(6),
  TIMEZONE_ID VARCHAR2(100)
);

CREATE UNIQUE INDEX BATCH_JOB_EXECUTION_PK ON BATCH_JOB_EXECUTION
(JOB_ID);

CREATE INDEX BATCH_JOB_EXECUTION_I1 ON BATCH_JOB_EXECUTION
(JOB_NAME, STATUS);

CREATE INDEX BATCH_JOB_EXECUTION_I2 ON BATCH_JOB_EXECUTION
(CREATE_TIME);

CREATE INDEX BATCH_JOB_EXECUTION_I3 ON BATCH_JOB_EXECUTION
(SERVER, STATUS, JOB_EXEC_YN, JOB_TYPE, JOB_ID);

CREATE INDEX BATCH_JOB_EXECUTION_I4 on BATCH_JOB_EXECUTION
(SERVER, STATUS, JOB_EXEC_YN, JOB_TYPE, CREATE_TIME);

CREATE INDEX BATCH_JOB_EXECUTION_I5 on BATCH_JOB_EXECUTION
(STATUS, JOB_TYPE, CREATE_TIME);

CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ;

----




[source, sql]
----

CREATE TABLE BATCH_STEP_EXECUTION
(
    JOB_ID                      NUMBER(19)     NOT NULL,
    STEP_ID                     NUMBER(19)     NOT NULL,
    STEP_NAME                   VARCHAR2(500)    NOT NULL,
    STATUS                      VARCHAR2(20),
    EXIT_MESSAGE                VARCHAR2(2500),
    LOG_FILE                    VARCHAR2(500),
    CREATE_TIME                 TIMESTAMP(6),
    UPDATE_TIME                 TIMESTAMP(6),
    SHORT_CONTEXT               VARCHAR2(2500),
    SERIALIZED_CONTEXT          CLOB,
    CPU_CURRENT                 NUMBER(5,2),
    CPU_AVERAGE                 NUMBER(5,2),
    MEMORY_TOTAL                NUMBER(20),
    MEMORY_FREE                 NUMBER(20),
    CURRENT_COUNT               NUMBER(38),
    TOTAL_COUNT                 NUMBER(38),
    COMMIT_COUNT                NUMBER(38),
    VERSION                     NUMBER(19,0),
  MAX_COMMIT_INTERVAL DECIMAL(38)
);

CREATE UNIQUE INDEX BATCH_STEP_EXECUTION_PK ON BATCH_STEP_EXECUTION
(JOB_ID, STEP_ID);

CREATE INDEX BATCH_STEP_EXECUTION_I1 ON BATCH_STEP_EXECUTION
(STEP_ID, STATUS);

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ;

----




[source, sql]
----

CREATE TABLE BATCH_RESOURCE_EXECUTION
(
    JOB_ID                      NUMBER(19)     NOT NULL,
    STEP_ID                     NUMBER(19)     NOT NULL,
    RESOURCE_NAME               VARCHAR2(500)    NOT NULL,
    URL                         VARCHAR2(2000),
    IO_TYPE                     VARCHAR2(10)     NOT NULL,
    RESOURCE_TYPE               VARCHAR2(10),
    STATUS                      VARCHAR2(10),
    CURRENT_COUNT               NUMBER(38),
    COMMIT_POS                  NUMBER(38),
    COMMIT_COUNT                NUMBER(38),
    CREATE_TIME                 TIMESTAMP(6),
    UPDATE_TIME                 TIMESTAMP(6)
);

CREATE UNIQUE INDEX BATCH_RESOURCE_EXECUTION_PK ON BATCH_RESOURCE_EXECUTION
(JOB_ID, STEP_ID, RESOURCE_NAME);

CREATE INDEX BATCH_RESOURCE_EXECUTION_I1 ON BATCH_RESOURCE_EXECUTION
(STEP_ID, RESOURCE_NAME);

CREATE INDEX BATCH_RESOURCE_EXECUTION_I2 ON BATCH_RESOURCE_EXECUTION
(URL, STATUS);

----

[source, sql]
----

CREATE TABLE BATCH_JOB_EXECUTION_EVENT
(
  JOB_ID      NUMBER(19)                       NOT NULL,
  EVENT_DATE  NUMBER(20)                 NOT NULL,
  EVENT_INFO  VARCHAR2(100),
  CONSTRAINT BATCH_JOB_EXECUTION_EVENT_PK PRIMARY KEY (JOB_ID, EVENT_DATE)
);

----

[source, sql]
----

CREATE TABLE BATCH_CONFIG
(
  SCHEDULING_TIME       VARCHAR2(30)      NOT NULL,
  LEADER_ADMIN_NAME      VARCHAR2(100)     ,
  LEADER_ADMIN_UPDATE_TIME TIMESTAMP,
  CONSTRAINT BATCH_CONFIG_PK PRIMARY KEY (SCHEDULING_TIME)
);

----


[source, sql]
----
CREATE TABLE BATCH_REPLACE_PARAM
(
  REPLACE_KEY VARCHAR2(100),
  REPLACE_TYPE VARCHAR2(30),
  REPLACE_VALUE VARCHAR2(100),
  REPLACE_OFFSET NUMBER(2),
  CONSTRAINT BATCH_REPLACE_PARAM_PK PRIMARY KEY (REPLACE_KEY)
);
----

[source, sql]
----

CREATE TABLE BATCH_TIMEZONE
(
  TIMEZONE_ID VARCHAR2(100),
  DEFAULT_YN VARCHAR2(1)
);

----